# Licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

name: IREE Runtime Template

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-20.04
    steps:
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install cmake clang ninja-build
    - name: Install IREE compiler
      run: |
        python -m pip install iree-compiler
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Initialize submodules
      run : |
        git \
            -c submodule."third_party/llvm-project".update=none \
            submodule update --init --recursive
    - name: Build sample
      run: |
        cd $GITHUB_WORKSPACE
        mkdir build && cd build
        cmake .. \
          -GNinja \
          -DCMAKE_C_COMPILER=clang-10 \
          -DCMAKE_CXX_COMPILER=clang++-10
        cmake --build . --target hello_world
    - name: Compile sample module
      run: |
        cd $GITHUB_WORKSPACE
        iree-compile \
          --iree-hal-target-backends=llvm-cpu \
          simple_mul.mlir \
          -o simple_mul.vmfb
    - name: Test execution
      run: |
        cd $GITHUB_WORKSPACE
        ./build/hello_world local-sync simple_mul.vmfb
